name: Push

on: push

jobs:
  test:
    name: Lint, build, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: sudo apt-get update && sudo apt-get install -y samtools
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
